name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.drupalcode.org/project/json_field_processor"
      env:
        GITLAB_HOSTNAME: "git.drupal.org"
        GITLAB_USERNAME: "homura163"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "167498"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
